name: Build and Deploy ASP.Net Core App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      # Build the project from the 'api' folder
      - name: Build with dotnet
        working-directory: api
        run: dotnet build --configuration Release

      # Publish the application to a folder named 'publish' in the 'api' directory
      - name: Publish the application
        working-directory: api
        run: dotnet publish -c Release -o publish

      # Upload the published output as an artifact named 'dotnet-app'
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: api/publish

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      # Download the published artifact
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy the artifact from the downloaded folder
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "hyv"
          slot-name: "Production"
          package: api/publish
